version: '3.8'
services:
  db:
    image: postgres:15
    container_name: shelterdb-postgres
    environment:
      POSTGRES_USER:  user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB:    shelterdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
# To run the PostgreSQL container, use the following command:
# docker run -d --name myapp-postgres --network myapp-net -e POSTGRES_USER=demo -e POSTGRES_PASSWORD=demo -e POSTGRES_DB=myapp -p 5432:5432 postgres:15
