spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
