name: Build

on:
  pull_request:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: |
      ${{ github.event_name == 'pull_request' }}
      || ${{ github.event_name == 'push' }}
      || ${{ github.event_name == 'repository_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 24

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Package artifact
        run: mvn package -B
